In [1]:
import spacy
!python -m spacy download en_core_web_lg

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 587.7/587.7 MB 2.9 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [2]:
import gensim.downloader as api
wv=api.load('word2vec-google-news-300')
glv=api.load('glove-twitter-25')

[==================================================] 100.0% 1662.8/1662.8MB downloaded
[==================================================] 100.0% 104.8/104.8MB downloaded


In [3]:
nlp=spacy.load('en_core_web_lg')

In [6]:
doc=nlp('dog cat banana dfsdds')
for token  in doc:
  print(token.text,"Vector: ",token.has_vector,"OOV: ",token.is_oov)

dog Vector:  True OOV:  False
cat Vector:  True OOV:  False
banana Vector:  True OOV:  False
dfsdds Vector:  False OOV:  True


In [7]:
doc[0].vector

array([ 1.2330e+00,  4.2963e+00, -7.9738e+00, -1.0121e+01,  1.8207e+00,
        1.4098e+00, -4.5180e+00, -5.2261e+00, -2.9157e-01,  9.5234e-01,
        6.9880e+00,  5.0637e+00, -5.5726e-03,  3.3395e+00,  6.4596e+00,
       -6.3742e+00,  3.9045e-02, -3.9855e+00,  1.2085e+00, -1.3186e+00,
       -4.8886e+00,  3.7066e+00, -2.8281e+00, -3.5447e+00,  7.6888e-01,
        1.5016e+00, -4.3632e+00,  8.6480e+00, -5.9286e+00, -1.3055e+00,
        8.3870e-01,  9.0137e-01, -1.7843e+00, -1.0148e+00,  2.7300e+00,
       -6.9039e+00,  8.0413e-01,  7.4880e+00,  6.1078e+00, -4.2130e+00,
       -1.5384e-01, -5.4995e+00,  1.0896e+01,  3.9278e+00, -1.3601e-01,
        7.7732e-02,  3.2218e+00, -5.8777e+00,  6.1359e-01, -2.4287e+00,
        6.2820e+00,  1.3461e+01,  4.3236e+00,  2.4266e+00, -2.6512e+00,
        1.1577e+00,  5.0848e+00, -1.7058e+00,  3.3824e+00,  3.2850e+00,
        1.0969e+00, -8.3711e+00, -1.5554e+00,  2.0296e+00, -2.6796e+00,
       -6.9195e+00, -2.3386e+00, -1.9916e+00, -3.0450e+00,  2.48

In [8]:
base_token=nlp('sandwich')

In [10]:
doc=nlp('bread sandwich burger car tiger human rice food')
for token in doc:
  print(f'{token.text} <-> {base_token.text}: {token.similarity(base_token)} ')

bread <-> sandwich: 0.6341067177397708 
sandwich <-> sandwich: 0.9999999823146835 
burger <-> sandwich: 0.7900927756758959 
car <-> sandwich: 0.1825516115154349 
tiger <-> sandwich: 0.11234834480413391 
human <-> sandwich: -0.042971604865238676 
rice <-> sandwich: 0.48384042420843604 
food <-> sandwich: 0.4348063691643022 


In [14]:
nlp('rich').similarity(nlp('wealthy'))

0.6305407704180923

In [15]:
def similar_words(base_word,words_to_compare):
  base_token=nlp(base_word)
  doc=nlp(words_to_compare)
  for token in doc:
    print(f'{token.text} <-> {base_token.text}: {token.similarity(base_token)}')

In [17]:
similar_words('iphone','apple samsung mobile mac')

apple <-> iphone: 0.4387907401919904
samsung <-> iphone: 0.670859081425417
mobile <-> iphone: 0.5803360612987323
mac <-> iphone: 0.3624556921558316


In [18]:
king=nlp.vocab['king'].vector
queen=nlp.vocab['queen'].vector
man=nlp.vocab['man'].vector
woman=nlp.vocab['woman'].vector
result=king-man+woman

In [23]:
from sklearn.metrics.pairwise import cosine_similarity

In [24]:
cosine_similarity([result],[queen])

array([[0.61780137]], dtype=float32)

In [25]:
france=nlp.vocab['France'].vector
paris=nlp.vocab['Paris'].vector
berlin=nlp.vocab['Berlin'].vector
germany=nlp.vocab['Germany'].vector
result=france-paris+berlin

In [26]:
cosine_similarity([result],[germany])

array([[0.8555054]], dtype=float32)

In [27]:
import pandas as pd

In [31]:
df=pd.read_csv('train.csv',sep=';')

In [32]:
df.head()

text  label
0  trump tell million american hurricane victim r...      0
1  new york cable provider altice acc network new...      0
2  japan dentsu get small fine overtime breach de...      1
3  little kid toxic stress solve priscilla chan c...      1
4  fantasy football kicker ranking week warn some...      0

In [34]:
df['label'].value_counts()

label
0    1670
1    1670
Name: count, dtype: int64

In [35]:
for i in range(len(df)):
  nlp(df['text'][i]).vector

'trump tell million american hurricane victim responsible trump tell million american hurricane victim responsible reader think story fact add two cent news president unite state tell million american face death disease responsible misfortune source http wwwcarbonatedtvnewsdonaldtrumppuertoricohurricanevictims'

In [36]:
df['vector']=df['text'].apply(lambda x:nlp(x).vector)

In [37]:
df.head()

text  label  \
0  trump tell million american hurricane victim r...      0   
1  new york cable provider altice acc network new...      0   
2  japan dentsu get small fine overtime breach de...      1   
3  little kid toxic stress solve priscilla chan c...      1   
4  fantasy football kicker ranking week warn some...      0   

                                              vector  
0  [-0.9175093, -0.6764788, -1.5303328, -0.118178...  
1  [-0.3940568, 0.9837707, -1.0420312, 0.18975376...  
2  [-0.5900704, 0.112972684, -1.7439389, 0.365226...  
3  [0.05492324, 1.2268136, -2.270063, -0.46489054...  
4  [0.24137406, 0.21209694, -0.40104523, 0.707117...

In [38]:
from sklearn.model_selection import train_test_split as tts

In [39]:
Xtr,Xte,ytr,yte=tts(df['vector'].values,df['label'],test_size=0.2,random_state=42)

In [40]:
Xtr.shape

(2672,)

In [41]:
import numpy as np

In [42]:
Xtr_stack=np.stack(Xtr)
Xte_stack=np.stack(Xte)

In [43]:
Xtr_stack.shape

(2672, 300)

In [44]:
from sklearn.naive_bayes import MultinomialNB

In [45]:
model=MultinomialNB()

In [47]:
from sklearn.preprocessing import MinMaxScaler

In [48]:
scaler=MinMaxScaler()

In [49]:
Xtr_scaled=scaler.fit_transform(Xtr_stack)
Xte_scaled=scaler.transform(Xte_stack)

In [50]:
model.fit(Xtr_scaled,ytr)

MultinomialNB()

In [51]:
y_pred=model.predict(Xte_scaled)

In [52]:
from sklearn.metrics import accuracy_score as acs

In [53]:
acs(yte,y_pred)

0.7155688622754491

In [54]:
from sklearn.metrics import classification_report as cr

In [55]:
print(cr(yte,y_pred))

              precision    recall  f1-score   support

           0       0.74      0.68      0.71       337
           1       0.70      0.75      0.72       331

    accuracy                           0.72       668
   macro avg       0.72      0.72      0.72       668
weighted avg       0.72      0.72      0.72       668

