In [4]:
import numpy as np

In [1]:
docs = ['recurrent neural network',
		'neural network',
		'artificial neural',
		'connections between nodes',
		'can create a cycle',
		'allowing output',
		'some nodes to affect subsequent',
		'exhibit temporal',
		'dynamic behavior',
		'type of Neural Network',
    'affect subsequent']

In [2]:
import tensorflow as tf

In [5]:
from keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer(oov_token="<nothing>")

In [6]:
tokenizer.fit_on_texts(docs)

In [7]:
tokenizer.word_index

{'<nothing>': 1,
 'neural': 2,
 'network': 3,
 'nodes': 4,
 'affect': 5,
 'subsequent': 6,
 'recurrent': 7,
 'artificial': 8,
 'connections': 9,
 'between': 10,
 'can': 11,
 'create': 12,
 'a': 13,
 'cycle': 14,
 'allowing': 15,
 'output': 16,
 'some': 17,
 'to': 18,
 'exhibit': 19,
 'temporal': 20,
 'dynamic': 21,
 'behavior': 22,
 'type': 23,
 'of': 24}

In [8]:
tokenizer.word_counts

OrderedDict([('recurrent', 1),
             ('neural', 4),
             ('network', 3),
             ('artificial', 1),
             ('connections', 1),
             ('between', 1),
             ('nodes', 2),
             ('can', 1),
             ('create', 1),
             ('a', 1),
             ('cycle', 1),
             ('allowing', 1),
             ('output', 1),
             ('some', 1),
             ('to', 1),
             ('affect', 2),
             ('subsequent', 2),
             ('exhibit', 1),
             ('temporal', 1),
             ('dynamic', 1),
             ('behavior', 1),
             ('type', 1),
             ('of', 1)])

In [9]:
tokenizer.document_count

11

In [10]:
sequences=tokenizer.texts_to_sequences(docs)

In [11]:
sequences

[[7, 2, 3],
 [2, 3],
 [8, 2],
 [9, 10, 4],
 [11, 12, 13, 14],
 [15, 16],
 [17, 4, 18, 5, 6],
 [19, 20],
 [21, 22],
 [23, 24, 2, 3],
 [5, 6]]

In [12]:
from keras.utils import pad_sequences

In [13]:
sequences=pad_sequences(sequences,maxlen=10,padding='post')

In [14]:
sequences

array([[ 7,  2,  3,  0,  0,  0,  0,  0,  0,  0],
       [ 2,  3,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 8,  2,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 9, 10,  4,  0,  0,  0,  0,  0,  0,  0],
       [11, 12, 13, 14,  0,  0,  0,  0,  0,  0],
       [15, 16,  0,  0,  0,  0,  0,  0,  0,  0],
       [17,  4, 18,  5,  6,  0,  0,  0,  0,  0],
       [19, 20,  0,  0,  0,  0,  0,  0,  0,  0],
       [21, 22,  0,  0,  0,  0,  0,  0,  0,  0],
       [23, 24,  2,  3,  0,  0,  0,  0,  0,  0],
       [ 5,  6,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int32)

In [21]:
#Sentiment analysis using RNN

In [22]:
from keras.datasets import imdb
(Xtr,ytr),(Xte,yte)=imdb.load_data()

17464789/17464789 [==============================] - 0s 0us/step


In [23]:
from keras import Sequential
from keras.layers import Dense, SimpleRNN,Embedding,Flatten

In [24]:
len(Xtr[0])

218

In [25]:
maxlen=500
Xtr_pad=pad_sequences(Xtr,maxlen,padding='post')
Xte_pad=pad_sequences(Xte,maxlen,padding='post')

In [26]:
model=Sequential()
model.add(SimpleRNN(32,input_shape=(500,1),return_sequences=False))
model.add(Dense(1,activation='sigmoid'))

In [27]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 32)                1088      
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1121 (4.38 KB)
Trainable params: 1121 (4.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [28]:
model.compile(metrics=['accuracy'],optimizer='adam',loss='binary_crossentropy')

In [29]:
model.fit(Xtr_pad,ytr,epochs=5,validation_data=(Xte_pad,yte),verbose=2)

Epoch 1/5
782/782 - 230s - loss: 0.6943 - accuracy: 0.5039 - val_loss: 0.6935 - val_accuracy: 0.5050 - 230s/epoch - 294ms/step
Epoch 2/5
782/782 - 227s - loss: 0.6938 - accuracy: 0.5028 - val_loss: 0.6935 - val_accuracy: 0.5068 - 227s/epoch - 290ms/step
Epoch 3/5
782/782 - 225s - loss: 0.6938 - accuracy: 0.5034 - val_loss: 0.6935 - val_accuracy: 0.5084 - 225s/epoch - 288ms/step
Epoch 4/5
782/782 - 228s - loss: 0.6938 - accuracy: 0.5041 - val_loss: 0.6950 - val_accuracy: 0.5036 - 228s/epoch - 292ms/step
Epoch 5/5
782/782 - 241s - loss: 0.6937 - accuracy: 0.5046 - val_loss: 0.6938 - val_accuracy: 0.5059 - 241s/epoch - 309ms/step


In [21]:
from keras.models import Sequential
from keras.layers import Embedding, Dense, SimpleRNN
model=Sequential()
model.add(Embedding(23,output_dim=2,input_length=500))
model.add(SimpleRNN(32,input_shape=(500,1),return_sequences=False))
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 500, 2)            46        
                                                                 
 simple_rnn (SimpleRNN)      (None, 32)                1120      
                                                                 
Total params: 1166 (4.55 KB)
Trainable params: 1166 (4.55 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [40]:
from keras.datasets import imdb
(Xtr,ytr),(Xte,yte)=imdb.load_data(num_words=10000)

In [41]:
from keras.utils import pad_sequences

In [50]:
Xtr_pad=pad_sequences(Xtr,maxlen=50,padding='post')
Xte_pad=pad_sequences(Xte,maxlen=50,padding='post')

In [51]:
Xtr_pad

array([[2071,   56,   26, ...,   19,  178,   32],
       [8255,    5,    2, ...,   16,  145,   95],
       [ 215,   28,  610, ...,    7,  129,  113],
       ...,
       [   4,   65,  496, ...,    4, 3586,    2],
       [  13,   18,   31, ...,   12,    9,   23],
       [7585,    8, 2197, ...,  204,  131,    9]], dtype=int32)

In [52]:
model=Sequential()
model.add(Embedding(input_dim=10000,output_dim=2,input_length=50))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1,activation='sigmoid'))
model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_8 (Embedding)     (None, 50, 2)             20000     
                                                                 
 simple_rnn_6 (SimpleRNN)    (None, 32)                1120      
                                                                 
 dense_4 (Dense)             (None, 1)                 33        
                                                                 
Total params: 21153 (82.63 KB)
Trainable params: 21153 (82.63 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [53]:
model.compile(metrics=['accuracy'],optimizer='adam',loss='binary_crossentropy')

In [54]:
model.fit(Xtr_pad,ytr,epochs=5,validation_data=(Xte_pad,yte),verbose=1)

Epoch 1/5
782/782 [==============================] - 19s 23ms/step - loss: 0.6314 - accuracy: 0.6076 - val_loss: 0.5283 - val_accuracy: 0.7472
Epoch 2/5
782/782 [==============================] - 14s 18ms/step - loss: 0.4144 - accuracy: 0.8163 - val_loss: 0.4584 - val_accuracy: 0.7939
Epoch 3/5
782/782 [==============================] - 14s 18ms/step - loss: 0.3308 - accuracy: 0.8614 - val_loss: 0.4378 - val_accuracy: 0.8087
Epoch 4/5
782/782 [==============================] - 16s 21ms/step - loss: 0.2856 - accuracy: 0.8861 - val_loss: 0.4429 - val_accuracy: 0.8031
Epoch 5/5
782/782 [==============================] - 16s 20ms/step - loss: 0.2509 - accuracy: 0.9028 - val_loss: 0.4853 - val_accuracy: 0.7985


In [58]:
Xte_pad[0][0:50].reshape(1,-1).shape

(1, 50)

In [59]:
model.predict(Xte_pad[0][0:50].reshape(1,-1))

1/1 [==============================] - 0s 289ms/step


array([[0.22734255]], dtype=float32)